package co.unicauca.cliente.restaurantathand.presentation;


import co.unicauca.cliente.restaurantathand.access.Factory;
import co.unicauca.cliente.restaurantathand.access.IRestaurantAccess;
import co.unicauca.cliente.restaurantathand.domain.entity.Admin;
import co.unicauca.cliente.restaurantathand.domain.entity.Restaurant;
import co.unicauca.cliente.restaurantathand.domain.service.RestaurantService;
import co.unicauca.cliente.restaurantathand.infra.Messages;
import static co.unicauca.cliente.restaurantathand.infra.Messages.successMessage;
import java.io.File;
import java.util.List;

import javax.swing.ImageIcon;
import javax.swing.JFileChooser;



/**
 *
 * @author Michelle Vallejo
 */
public class GUICrearRest1 extends javax.swing.JInternalFrame{

    
    /**
     * Creates new form GUICrearRest
     */
    ImageIcon iconobtn = new ImageIcon("src/main/java/resource/mas.png");
    ImageIcon iconolbl = new ImageIcon("src/main/java/resource/check.png");
    
    /*
     * administrador del restaurante
    */   
    
    private Admin admin;
    
    /**
     * Almacena una lista de restaurantes
     */
    private List<Restaurant> restaurants;
    
    /*
     * Restaurante que vamos a seleccionar
     */
    public Restaurant restaurantUpdate;
    
    
    public GUICrearRest1() {
        initComponents();
        lblLogo.setIcon(iconolbl);
        btnRegistrarRest.setIcon(iconobtn); 
        
    }

    public GUICrearRest1(Admin admin) {
        initComponents();
        lblLogo.setIcon(iconolbl);
        btnRegistrarRest.setIcon(iconobtn);
        this.admin = admin;
        btnGuardarCambios.setVisible(false);
        //btnGuardarCambios.setEnabled(false);
        admin.setRestaurants(restaurants);
    }
    
    /*
     * Cambiar la interfaz´para que actualice en vez de Registrar
     */
    public void activarActualizar( ){
        btnGuardarCambios.setVisible(true);
        btnRegistrarRest.setVisible(false);
        llenarCampos();
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlCentro = new javax.swing.JPanel();
        lblNitRest = new javax.swing.JLabel();
        txtNitRest = new javax.swing.JTextField();
        lblRequeNit = new javax.swing.JLabel();
        lblNameRest = new javax.swing.JLabel();
        txtNameRest = new javax.swing.JTextField();
        lblRequeName = new javax.swing.JLabel();
        lblAddressRest = new javax.swing.JLabel();
        txtAddressRest = new javax.swing.JTextField();
        lblRequeAddress = new javax.swing.JLabel();
        lblCityRest = new javax.swing.JLabel();
        txtCityRest = new javax.swing.JTextField();
        lblRequeCity = new javax.swing.JLabel();
        lblPhoneRest = new javax.swing.JLabel();
        txtPhoneRest = new javax.swing.JTextField();
        lblRequePhone = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        txtEmailRest = new javax.swing.JTextField();
        lblRequeEmail = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtImagen = new javax.swing.JTextField();
        btnBuscarImagen = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        btnRegistrarRest = new javax.swing.JButton();
        btnGuardarCambios = new javax.swing.JButton();
        pnlNorte = new javax.swing.JPanel();
        lblLogo = new javax.swing.JLabel();

        setBackground(new java.awt.Color(153, 153, 255));
        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);

        pnlCentro.setBackground(new java.awt.Color(255, 255, 255));
        pnlCentro.setPreferredSize(new java.awt.Dimension(393, 157));
        pnlCentro.setLayout(new java.awt.GridLayout(8, 3));

        lblNitRest.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblNitRest.setText("Nit: ");
        pnlCentro.add(lblNitRest);
        pnlCentro.add(txtNitRest);

        lblRequeNit.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblRequeNit.setText("Requerido");
        lblRequeNit.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        pnlCentro.add(lblRequeNit);

        lblNameRest.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblNameRest.setText("Name:");
        pnlCentro.add(lblNameRest);
        pnlCentro.add(txtNameRest);

        lblRequeName.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblRequeName.setText("Requerido");
        lblRequeName.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        pnlCentro.add(lblRequeName);

        lblAddressRest.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblAddressRest.setText("Address:");
        pnlCentro.add(lblAddressRest);
        pnlCentro.add(txtAddressRest);

        lblRequeAddress.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblRequeAddress.setText("Requerido");
        lblRequeAddress.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        pnlCentro.add(lblRequeAddress);

        lblCityRest.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblCityRest.setText("City:");
        pnlCentro.add(lblCityRest);
        pnlCentro.add(txtCityRest);

        lblRequeCity.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblRequeCity.setText("Requerido");
        lblRequeCity.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        pnlCentro.add(lblRequeCity);

        lblPhoneRest.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblPhoneRest.setText("Phone:");
        pnlCentro.add(lblPhoneRest);
        pnlCentro.add(txtPhoneRest);

        lblRequePhone.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblRequePhone.setText("Requerido");
        lblRequePhone.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        pnlCentro.add(lblRequePhone);

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Email:");
        pnlCentro.add(jLabel1);
        pnlCentro.add(txtEmailRest);

        lblRequeEmail.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblRequeEmail.setText("Requerido");
        lblRequeEmail.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        pnlCentro.add(lblRequeEmail);

        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Imagen:");
        pnlCentro.add(jLabel2);
        pnlCentro.add(txtImagen);

        btnBuscarImagen.setText("Buscar");
        btnBuscarImagen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarImagenActionPerformed(evt);
            }
        });
        pnlCentro.add(btnBuscarImagen);
        pnlCentro.add(jLabel4);

        btnRegistrarRest.setText("Registrar");
        btnRegistrarRest.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegistrarRestActionPerformed(evt);
            }
        });
        pnlCentro.add(btnRegistrarRest);

        btnGuardarCambios.setText("Guardar Cambios");
        btnGuardarCambios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarCambiosActionPerformed(evt);
            }
        });
        pnlCentro.add(btnGuardarCambios);

        pnlNorte.setBackground(new java.awt.Color(153, 153, 255));
        pnlNorte.setLayout(new java.awt.GridLayout(1, 0));

        lblLogo.setBackground(new java.awt.Color(255, 255, 255));
        lblLogo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblLogo.setMaximumSize(new java.awt.Dimension(393, 56));
        lblLogo.setMinimumSize(new java.awt.Dimension(393, 56));
        lblLogo.setPreferredSize(new java.awt.Dimension(393, 28));
        pnlNorte.add(lblLogo);
        lblLogo.getAccessibleContext().setAccessibleName("holi");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pnlNorte, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pnlCentro, javax.swing.GroupLayout.DEFAULT_SIZE, 618, Short.MAX_VALUE))
                .addGap(6, 6, 6))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(pnlNorte, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pnlCentro, javax.swing.GroupLayout.DEFAULT_SIZE, 434, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnRegistrarRestActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistrarRestActionPerformed
       IRestaurantAccess service = Factory.getInstance().getRestaurantService();
       // Inyecta la dependencia
       
       String nit = txtNitRest.getText();
       String name = txtNameRest.getText();
       String address = txtAddressRest.getText();
       String city = txtCityRest.getText();
       String phone = txtPhoneRest.getText();
       String email = txtEmailRest.getText();
       
       if (nit.equals("") || name.equals("") || address.equals("")
           || city.equals("") || phone.equals("") || email.equals("")) {
            
            Messages.warningMessage("ERROR AL CREAR EL RESTAURANTE: \nCampos vacios", "Warning");
            return;
        }
       
        RestaurantService restaurantService = new RestaurantService(service);
        Restaurant restaurant = new Restaurant();
        restaurant.setAtrAddressRest(address);
        restaurant.setAtrAdmiRest(admin.getAtrUserName());
        restaurant.setAtrCityRest(city);
        restaurant.setAtrEmailRest(email);
        restaurant.setAtrMobileRest(phone);
        restaurant.setAtrNameRest(name);
        restaurant.setAtrNitRest(nit);
        
        try {
            if (restaurantService.createRestaurant(restaurant)) {
                successMessage("Restaurante agregada con éxito.", "Atención");
                limpiarDatos();
                
            }else{
                Messages.warningMessage("En el sistema se encuentra registrado ya un Restaurante con ese NIt", "Warning");
            }
        } catch (Exception ex) {
            successMessage(ex.getMessage(), "Atención");
        }
      
        btnRegistrarRest.setEnabled(true);
       
    }//GEN-LAST:event_btnRegistrarRestActionPerformed

    private void btnBuscarImagenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarImagenActionPerformed
        // TODO add your handling code here:
        JFileChooser chooser= new JFileChooser();
        chooser.showOpenDialog(null);
        File f = chooser.getSelectedFile();
        String fileName = f.getAbsolutePath();
        txtImagen.setText(fileName);
    }//GEN-LAST:event_btnBuscarImagenActionPerformed

    private void btnGuardarCambiosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarCambiosActionPerformed
        IRestaurantAccess service = Factory.getInstance().getRestaurantService();
       // Inyecta la dependencia
       
       String nit = txtNitRest.getText();
       String name = txtNameRest.getText();
       String address = txtAddressRest.getText();
       String city = txtCityRest.getText();
       String phone = txtPhoneRest.getText();
       String email = txtEmailRest.getText();
       
       if (nit.equals("") || name.equals("") || address.equals("")
           || city.equals("") || phone.equals("") || email.equals("")) {
            
            Messages.warningMessage("ERROR AL ACTUALIZAR EL RESTAURANTE: \nCampos vacios", "Warning");
            return;
        }
       
        RestaurantService restaurantService = new RestaurantService(service);
        try {
            
            if (restaurantService.updateRestaurant(nit,name,address,phone,email,city,admin.getAtrUserName())) {
                successMessage("Restaurante actualizado con éxito.", "Atención"); 
            }else{
                Messages.warningMessage("el Restaurante no pudo ser actualizado", "Warning");
            }
        } catch (Exception ex) {
            successMessage(ex.getMessage(), "Atención");
        }
    }//GEN-LAST:event_btnGuardarCambiosActionPerformed
    
    public void limpiarDatos() {
        txtNitRest.setText("");
        txtNameRest.setText("");
        txtAddressRest.setText("");
        txtCityRest.setText("");
        txtPhoneRest.setText("");
        txtEmailRest.setText("");
        
    }
    
    public void llenarCampos (){
        txtNitRest.setText(restaurantUpdate.getAtrNitRest());
        txtNitRest.setEditable(false);
        txtNameRest.setText(restaurantUpdate.getAtrNameRest());
        txtAddressRest.setText(restaurantUpdate.getAtrAddressRest());
        txtCityRest.setText(restaurantUpdate.getAtrCityRest());
        txtPhoneRest.setText(restaurantUpdate.getAtrMobileRest());
        txtEmailRest.setText(restaurantUpdate.getAtrEmailRest());
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBuscarImagen;
    private javax.swing.JButton btnGuardarCambios;
    private javax.swing.JButton btnRegistrarRest;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel lblAddressRest;
    private javax.swing.JLabel lblCityRest;
    private javax.swing.JLabel lblLogo;
    private javax.swing.JLabel lblNameRest;
    private javax.swing.JLabel lblNitRest;
    private javax.swing.JLabel lblPhoneRest;
    private javax.swing.JLabel lblRequeAddress;
    private javax.swing.JLabel lblRequeCity;
    private javax.swing.JLabel lblRequeEmail;
    private javax.swing.JLabel lblRequeName;
    private javax.swing.JLabel lblRequeNit;
    private javax.swing.JLabel lblRequePhone;
    private javax.swing.JPanel pnlCentro;
    private javax.swing.JPanel pnlNorte;
    private javax.swing.JTextField txtAddressRest;
    private javax.swing.JTextField txtCityRest;
    private javax.swing.JTextField txtEmailRest;
    private javax.swing.JTextField txtImagen;
    private javax.swing.JTextField txtNameRest;
    private javax.swing.JTextField txtNitRest;
    private javax.swing.JTextField txtPhoneRest;
    // End of variables declaration//GEN-END:variables

}
