
package co.unicauca.cliente.restaurantathand.presentation;


import co.unicauca.cliente.restaurantathand.access.Factory;
import co.unicauca.cliente.restaurantathand.access.IUserAccess;
import co.unicauca.cliente.restaurantathand.domain.entity.Admin;
import co.unicauca.cliente.restaurantathand.domain.entity.User;
import co.unicauca.cliente.restaurantathand.domain.service.UserService;
import co.unicauca.cliente.restaurantathand.infra.Messages;
import static co.unicauca.cliente.restaurantathand.infra.Messages.successMessage;
import static java.awt.Frame.NORMAL;
import javax.swing.ImageIcon;



/**
 *
 * @author Michelle Vallejo
 */
public class GUICrearCliente1 extends javax.swing.JFrame {

    /**
     * Creates new form PruebaCrearCut
     */
    
    ImageIcon iconobtn = new ImageIcon("src/main/java/resource/agregar.png");
    ImageIcon iconolbl = new ImageIcon("src/main/java/resource/checkcust.png");
    ImageIcon iconoMn = new ImageIcon("src/main/java/resource/flecha-hacia-atras.png");
    
    public GUICrearCliente1() {
     
        initComponents();
        lblLogo.setIcon(iconolbl);
        btnCrearCust.setIcon(iconobtn);
        jMenu1.setIcon(iconoMn);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlCentro = new javax.swing.JPanel();
        lblUserNameCli = new javax.swing.JLabel();
        txtUserNameCli = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        lblIdCli = new javax.swing.JLabel();
        txtIdCli = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        lblNameCli = new javax.swing.JLabel();
        txtNameCli = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        lblLastnameCli = new javax.swing.JLabel();
        txtLastnameCli = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        lblPasswordCli = new javax.swing.JLabel();
        txtPassword = new javax.swing.JPasswordField();
        jLabel9 = new javax.swing.JLabel();
        lblCityCli = new javax.swing.JLabel();
        txtCityCli = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        lblAddressCli = new javax.swing.JLabel();
        txtAddressCli = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        lblPhoneCli = new javax.swing.JLabel();
        txtPhone = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        lblTypeCli = new javax.swing.JLabel();
        cbxTypeCli = new javax.swing.JComboBox<>();
        jLabel7 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        btnCrearCust = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        pnlNorte = new javax.swing.JPanel();
        lblLogo = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));

        pnlCentro.setBackground(new java.awt.Color(255, 255, 255));
        pnlCentro.setLayout(new java.awt.GridLayout(11, 1));

        lblUserNameCli.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblUserNameCli.setText("User name:");
        pnlCentro.add(lblUserNameCli);
        pnlCentro.add(txtUserNameCli);

        jLabel1.setText("Requerido");
        pnlCentro.add(jLabel1);

        lblIdCli.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblIdCli.setText("Identification:");
        pnlCentro.add(lblIdCli);
        pnlCentro.add(txtIdCli);

        jLabel2.setText("Requerido");
        pnlCentro.add(jLabel2);

        lblNameCli.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblNameCli.setText("Name:");
        pnlCentro.add(lblNameCli);
        pnlCentro.add(txtNameCli);

        jLabel4.setText("Requerido");
        pnlCentro.add(jLabel4);

        lblLastnameCli.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblLastnameCli.setText("Lastname:");
        pnlCentro.add(lblLastnameCli);
        pnlCentro.add(txtLastnameCli);

        jLabel3.setText("Requerido");
        pnlCentro.add(jLabel3);

        lblPasswordCli.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblPasswordCli.setText("Password:");
        pnlCentro.add(lblPasswordCli);
        pnlCentro.add(txtPassword);

        jLabel9.setText("Requerido");
        pnlCentro.add(jLabel9);

        lblCityCli.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblCityCli.setText("City:");
        pnlCentro.add(lblCityCli);
        pnlCentro.add(txtCityCli);

        jLabel8.setText("Requerido");
        pnlCentro.add(jLabel8);

        lblAddressCli.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblAddressCli.setText("Address:");
        pnlCentro.add(lblAddressCli);
        pnlCentro.add(txtAddressCli);

        jLabel6.setText("Requerido");
        pnlCentro.add(jLabel6);

        lblPhoneCli.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblPhoneCli.setText("Phone:");
        pnlCentro.add(lblPhoneCli);
        pnlCentro.add(txtPhone);

        jLabel5.setText("Requerido");
        pnlCentro.add(jLabel5);

        lblTypeCli.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTypeCli.setText("Type:");
        pnlCentro.add(lblTypeCli);

        cbxTypeCli.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "admin", "user" }));
        pnlCentro.add(cbxTypeCli);

        jLabel7.setText("Requerido");
        pnlCentro.add(jLabel7);
        pnlCentro.add(jLabel12);
        pnlCentro.add(jLabel14);
        pnlCentro.add(jLabel15);
        pnlCentro.add(jLabel11);

        btnCrearCust.setText("Crear");
        btnCrearCust.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCrearCustActionPerformed(evt);
            }
        });
        pnlCentro.add(btnCrearCust);
        pnlCentro.add(jLabel10);

        getContentPane().add(pnlCentro, java.awt.BorderLayout.CENTER);

        pnlNorte.setBackground(new java.awt.Color(255, 231, 231));
        pnlNorte.setMaximumSize(new java.awt.Dimension(393, 54));
        pnlNorte.setMinimumSize(new java.awt.Dimension(393, 56));
        pnlNorte.setPreferredSize(new java.awt.Dimension(393, 120));
        pnlNorte.setLayout(new java.awt.GridLayout(1, 0));

        lblLogo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblLogo.setMaximumSize(new java.awt.Dimension(393, 20));
        lblLogo.setMinimumSize(new java.awt.Dimension(393, 20));
        lblLogo.setPreferredSize(new java.awt.Dimension(393, 20));
        pnlNorte.add(lblLogo);
        lblLogo.getAccessibleContext().setAccessibleName("holi");

        getContentPane().add(pnlNorte, java.awt.BorderLayout.PAGE_START);

        jMenuBar1.setBackground(new java.awt.Color(255, 231, 231));
        jMenuBar1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 231, 231)));
        jMenuBar1.setForeground(new java.awt.Color(255, 231, 231));

        jMenu1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        jMenu1.setText("Back");
        jMenu1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenu1ActionPerformed(evt);
            }
        });
        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCrearCustActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCrearCustActionPerformed
      IUserAccess service = Factory.getInstance().getUserService();
       // Inyecta la dependencia
       
       String userName = txtUserNameCli.getText();
       String identificacion = txtIdCli.getText();
       String name = txtNameCli.getText();
       String lastname = txtLastnameCli.getText();
       String password = txtPassword.getText();
       String city = txtCityCli.getText();
       String address = txtAddressCli.getText();
       String phone = txtPhone.getText();
       String type = cbxTypeCli.getSelectedItem().toString();
       
       if (userName.equals("") || identificacion.equals("") || name.equals("")
           || lastname.equals("") || password.equals("") || city.equals("")
           || address.equals("") || phone.equals("") || type.equals("")) {
            
            Messages.warningMessage("ERROR AL CREAR EL CLIENTE: \nCampos vacios", "Warning");
            return;
        }
       
        UserService userService = new UserService(service);
        User user = new User();
        user.setAtrAddress(address);
        user.setAtrCity(city);
        user.setAtrIdentification(identificacion);
        user.setAtrLastName(lastname);
        user.setAtrName(name);
        user.setAtrPassword(password);
        user.setAtrPhone(phone);
        user.setAtrType(type);
        user.setAtrUserName(userName);
        
        try {
            if (userService.createUser(user)) {
                successMessage("Cliente agregada con éxito.", "Atención");
                if("admin".equals(type)){
                    Admin admin = new Admin();
                    admin.setAtrAddress(user.getAtrAddress());
                    admin.setAtrCity(user.getAtrCity());
                    admin.setAtrIdentification(user.getAtrIdentification());
                    admin.setAtrLastName(user.getAtrLastName());
                    admin.setAtrName(user.getAtrName());
                    admin.setAtrPassword(user.getAtrPassword());
                    admin.setAtrPhone(user.getAtrPhone());
                    admin.setAtrType(user.getAtrType());
                    admin.setAtrUserName(user.getAtrUserName());
                    GUIAdminMenu1 ins = null;
                    ins = new GUIAdminMenu1(admin);
                    ins.setExtendedState(NORMAL);
                    ins.setVisible(true);
                        
                    this.dispose();
                }else{
                    java.awt.EventQueue.invokeLater(new Runnable() {
                        public void run() {

                            GUICustomerRest1 ins = null;
                            ins = new GUICustomerRest1();
                            ins.setExtendedState(NORMAL);
                            ins.setVisible(true);
                        }
                    });

                this.dispose();
                }
            } else {
                    Messages.warningMessage("El Cliente no pudo ser agregado", "Warning");
            }
        } catch (Exception ex) {
            successMessage(ex.getMessage(), "Atención");
        }
     
    }//GEN-LAST:event_btnCrearCustActionPerformed

    private void jMenu1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenu1ActionPerformed
        

                GUILoginRest1 ins = null;
                ins = new GUILoginRest1();
                ins.setExtendedState(NORMAL);
                ins.setVisible(true);
        

        this.dispose();
    }//GEN-LAST:event_jMenu1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GUICrearCliente1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GUICrearCliente1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GUICrearCliente1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GUICrearCliente1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GUICrearCliente1().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCrearCust;
    private javax.swing.JComboBox<String> cbxTypeCli;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JLabel lblAddressCli;
    private javax.swing.JLabel lblCityCli;
    private javax.swing.JLabel lblIdCli;
    private javax.swing.JLabel lblLastnameCli;
    private javax.swing.JLabel lblLogo;
    private javax.swing.JLabel lblNameCli;
    private javax.swing.JLabel lblPasswordCli;
    private javax.swing.JLabel lblPhoneCli;
    private javax.swing.JLabel lblTypeCli;
    private javax.swing.JLabel lblUserNameCli;
    private javax.swing.JPanel pnlCentro;
    private javax.swing.JPanel pnlNorte;
    private javax.swing.JTextField txtAddressCli;
    private javax.swing.JTextField txtCityCli;
    private javax.swing.JTextField txtIdCli;
    private javax.swing.JTextField txtLastnameCli;
    private javax.swing.JTextField txtNameCli;
    private javax.swing.JPasswordField txtPassword;
    private javax.swing.JTextField txtPhone;
    private javax.swing.JTextField txtUserNameCli;
    // End of variables declaration//GEN-END:variables

}
