package co.unicauca.cliente.restaurantathand.presentation;

import java.beans.PropertyVetoException;
import static java.lang.System.exit;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author Michelle Vallejo
 */
public class GUICustomerRest1 extends javax.swing.JFrame {

    /**
     * Creates new form GUICustomerRest
     */
    ImageIcon iconoUser = new ImageIcon("src/main/java/resource/usuario.png");
    ImageIcon iconoBuscar = new ImageIcon("src/main/java/resource/seo.png");
    ImageIcon iconoFondoUsuario = new ImageIcon("src/main/java/resource/FondoUsuario.png");
    
    
    public GUICustomerRest1() {
        initComponents();
        mnuPerfil.setIcon(iconoUser);
        mnuGestRestaurantCust.setIcon(iconoBuscar);
        lblFondoInicio.setIcon(iconoFondoUsuario);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        dskEscritorio = new javax.swing.JDesktopPane();
        lblFondoInicio = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        mnuPerfil = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        mnuGestRestaurantCust = new javax.swing.JMenu();
        mnuBuscarRest = new javax.swing.JMenuItem();
        mnuRestEscogido = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new java.awt.GridLayout(1, 0));

        dskEscritorio.setBackground(new java.awt.Color(0, 0, 0));

        lblFondoInicio.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        dskEscritorio.setLayer(lblFondoInicio, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout dskEscritorioLayout = new javax.swing.GroupLayout(dskEscritorio);
        dskEscritorio.setLayout(dskEscritorioLayout);
        dskEscritorioLayout.setHorizontalGroup(
            dskEscritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblFondoInicio, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 400, Short.MAX_VALUE)
        );
        dskEscritorioLayout.setVerticalGroup(
            dskEscritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblFondoInicio, javax.swing.GroupLayout.DEFAULT_SIZE, 278, Short.MAX_VALUE)
        );

        getContentPane().add(dskEscritorio);

        mnuPerfil.setText("Perfil");

        jMenuItem1.setText("Administrar Cuenta");
        mnuPerfil.add(jMenuItem1);

        jMenuItem2.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_S, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        jMenuItem2.setText("Cerrar Sesion");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        mnuPerfil.add(jMenuItem2);

        jMenuBar1.add(mnuPerfil);

        mnuGestRestaurantCust.setText("Gestion Restaurante");

        mnuBuscarRest.setText("Buscar Restaurante");
        mnuBuscarRest.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuBuscarRestActionPerformed(evt);
            }
        });
        mnuGestRestaurantCust.add(mnuBuscarRest);

        mnuRestEscogido.setText("Restaurante Seleccionado");
        mnuRestEscogido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuRestEscogidoActionPerformed(evt);
            }
        });
        mnuGestRestaurantCust.add(mnuRestEscogido);

        jMenuBar1.add(mnuGestRestaurantCust);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void mnuBuscarRestActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuBuscarRestActionPerformed
        // TODO add your handling code here:
        GUIListarRestaurantesCustomer objListarRest  = new GUIListarRestaurantesCustomer(dskEscritorio);
        dskEscritorio.add(objListarRest);
        
        try {
                objListarRest.setMaximum(true);
            } catch (PropertyVetoException ex) {
                Logger.getLogger(GUIListarRestaurantesCustomer.class.getName()).log(Level.SEVERE, null, ex);
            }
            objListarRest.show();
    }//GEN-LAST:event_mnuBuscarRestActionPerformed

    private void mnuRestEscogidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuRestEscogidoActionPerformed
        // TODO add your handling code here:
        GUIRestauranteEscogido objRestElegido  = new GUIRestauranteEscogido();
        dskEscritorio.add(objRestElegido);
        
        try {
                objRestElegido.setMaximum(true);
            } catch (PropertyVetoException ex) {
                Logger.getLogger(GUICrearRest.class.getName()).log(Level.SEVERE, null, ex);
            }
            objRestElegido.show();
    }//GEN-LAST:event_mnuRestEscogidoActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        // TODO add your handling code here:
        if (JOptionPane.showConfirmDialog(rootPane, "¿Desea cerrar sesion ?",
                            "Cerrar Sesion", JOptionPane.WARNING_MESSAGE, JOptionPane.YES_NO_OPTION) == JOptionPane.YES_OPTION){
            GUILoginRest1 ins = null;
            ins = new GUILoginRest1();
            ins.setExtendedState(NORMAL);
            ins.setVisible(true);
            this.setVisible(false);
        } 
      
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    /**
     * @param args the command line arguments
     */
    /*public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
     /*   try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GUICustomerRest1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GUICustomerRest1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GUICustomerRest1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GUICustomerRest1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        /*java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GUICustomerRest1().setVisible(true);
            }
        });
    }*/

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDesktopPane dskEscritorio;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JLabel lblFondoInicio;
    private javax.swing.JMenuItem mnuBuscarRest;
    private javax.swing.JMenu mnuGestRestaurantCust;
    private javax.swing.JMenu mnuPerfil;
    private javax.swing.JMenuItem mnuRestEscogido;
    // End of variables declaration//GEN-END:variables
}
