package co.unicauca.cliente.restaurantathand.presentation;

import co.unicauca.cliente.restaurantathand.access.Factory;
import co.unicauca.cliente.restaurantathand.access.IRestaurantAccess;
import co.unicauca.cliente.restaurantathand.domain.entity.Restaurant;
import co.unicauca.cliente.restaurantathand.domain.service.RestaurantService;
import static co.unicauca.cliente.restaurantathand.infra.Messages.successMessage;
import java.beans.PropertyVetoException;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JDesktopPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Michelle Vallejo
 */
public final class GUIListarRestaurantesCustomer extends javax.swing.JInternalFrame {

    /**
     * Creates new form GUIListarRestaurantes
     */
    
    /**
     * Almacena una lista de restaurantes
     */
    private List<Restaurant> restaurants;
    
    /**
     * Restaurante Seleccionado 
     */
    
    public Restaurant restauranteSeleccionado;
    
    private JDesktopPane dskEscritorio;
    
    private int seleccionar;
    
    ImageIcon iconolbl = new ImageIcon("src/main/java/resource/bienvenido.png");
    
    public GUIListarRestaurantesCustomer() {
        initComponents();
        lblLogo.setIcon(iconolbl);
        cargarLista();
        cargarDatosTabla();
        txtCiudad.setEnabled(false);
        txtNombreRest.setEnabled(false);
        btnBuscar.setEnabled(false);
        btnVerMenu.setEnabled(false);
    }

    GUIListarRestaurantesCustomer(JDesktopPane dskEscritorio) {
        initComponents();
        lblLogo.setIcon(iconolbl);
        cargarLista();
        cargarDatosTabla();
        txtCiudad.setEnabled(false);
        txtNombreRest.setEnabled(false);
        btnBuscar.setEnabled(false); 
        btnVerMenu.setEnabled(false);
        this.dskEscritorio = dskEscritorio;
    }

    /**
     * Carga un lista a traves de una API REST
     */
    private void cargarLista() {
        IRestaurantAccess service = Factory.getInstance().getRestaurantService();
        // Inyecta la dependencia
        RestaurantService restaurant = new RestaurantService(service);

        try {
            restaurants = restaurant.listRestaurants();
        } catch (Exception ex) {
            successMessage(ex.getMessage(), "Atención");
        }
    }
    
    public void cargarDatosTabla() {
        tblListarRest.setDefaultRenderer(Object.class, new Render());
        
        DefaultTableModel model = (DefaultTableModel) tblListarRest.getModel();
        limpiarTabla(model);
        Object rowData[] = new Object[6];
        for (Restaurant restaurent : restaurants) {
            rowData[0] = restaurent.getAtrNitRest();
            rowData[1] = restaurent.getAtrNameRest();
            rowData[2] = restaurent.getAtrAddressRest();
            rowData[3] = restaurent.getAtrCityRest();
            rowData[4] = restaurent.getAtrMobileRest();
            rowData[5] = restaurent.getAtrEmailRest();
            model.addRow(rowData);
        }
    }

    
    public void limpiarTabla(DefaultTableModel objTabla) {
        while (objTabla.getRowCount()
                > 0) {
            objTabla.removeRow(0);
        }
    }
    
    public void habilitar (){
        if (cbxFiltrar.getSelectedItem().toString().equals("Nombre Restaurante")){
            txtCiudad.setText("");
            txtCiudad.setEnabled(false);
            txtNombreRest.setEnabled(true);
            btnBuscar.setEnabled(true);
            
        }
        else if (cbxFiltrar.getSelectedItem().toString().equals("Ciudad Restaurante")){
            txtNombreRest.setText("");
            txtNombreRest.setEnabled(false);
            txtCiudad.setEnabled(true);
            btnBuscar.setEnabled(true);
           
        }
        else{
            txtCiudad.setEnabled(false);
            txtNombreRest.setEnabled(false);
            btnBuscar.setEnabled(false);
        }
    
    } 
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlCentro = new javax.swing.JPanel();
        lblImagenRest = new javax.swing.JLabel();
        lblFiltrarPor = new javax.swing.JLabel();
        lblNombreRest = new javax.swing.JLabel();
        lblCiudadRest = new javax.swing.JLabel();
        btnBuscar = new javax.swing.JButton();
        btnSelccionar = new javax.swing.JButton();
        btnVerMenu = new javax.swing.JButton();
        btnDesceleccionar = new javax.swing.JButton();
        cbxFiltrar = new javax.swing.JComboBox<>();
        txtNombreRest = new javax.swing.JTextField();
        txtCiudad = new javax.swing.JTextField();
        pnlNorte = new javax.swing.JPanel();
        lblLogo = new javax.swing.JLabel();
        pnlSur = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblListarRest = new javax.swing.JTable();

        setBackground(new java.awt.Color(255, 255, 255));
        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);

        pnlCentro.setBackground(new java.awt.Color(255, 255, 255));

        lblImagenRest.setText("jLabel3");

        lblFiltrarPor.setText("Filtrar por:");

        lblNombreRest.setText("Nombre:");

        lblCiudadRest.setText("Ciudad:");

        btnBuscar.setText("Buscar");

        btnSelccionar.setText("Seleccionar");
        btnSelccionar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSelccionarActionPerformed(evt);
            }
        });

        btnVerMenu.setText("Ver Menu");
        btnVerMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVerMenuActionPerformed(evt);
            }
        });

        btnDesceleccionar.setText("Desceleccionar");

        cbxFiltrar.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Nombre Restaurante", "Ciudad Restaurante" }));
        cbxFiltrar.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cbxFiltrarItemStateChanged(evt);
            }
        });

        javax.swing.GroupLayout pnlCentroLayout = new javax.swing.GroupLayout(pnlCentro);
        pnlCentro.setLayout(pnlCentroLayout);
        pnlCentroLayout.setHorizontalGroup(
            pnlCentroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlCentroLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblImagenRest, javax.swing.GroupLayout.DEFAULT_SIZE, 146, Short.MAX_VALUE)
                .addGroup(pnlCentroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlCentroLayout.createSequentialGroup()
                        .addGap(94, 94, 94)
                        .addComponent(btnBuscar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(62, 62, 62)
                        .addComponent(btnSelccionar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(57, 57, 57)
                        .addComponent(btnVerMenu, javax.swing.GroupLayout.DEFAULT_SIZE, 96, Short.MAX_VALUE)
                        .addGap(51, 51, 51)
                        .addComponent(btnDesceleccionar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(28, 28, 28))
                    .addGroup(pnlCentroLayout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addGroup(pnlCentroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, pnlCentroLayout.createSequentialGroup()
                                .addComponent(lblCiudadRest, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(93, 93, 93))
                            .addGroup(pnlCentroLayout.createSequentialGroup()
                                .addGroup(pnlCentroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(pnlCentroLayout.createSequentialGroup()
                                        .addComponent(lblNombreRest, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addGap(22, 22, 22))
                                    .addGroup(pnlCentroLayout.createSequentialGroup()
                                        .addComponent(lblFiltrarPor, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addGap(16, 16, 16)))
                                .addGroup(pnlCentroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(cbxFiltrar, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(txtCiudad, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(txtNombreRest))))
                        .addGap(320, 320, 320))))
        );
        pnlCentroLayout.setVerticalGroup(
            pnlCentroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlCentroLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlCentroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlCentroLayout.createSequentialGroup()
                        .addGroup(pnlCentroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnlCentroLayout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addComponent(lblFiltrarPor, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(pnlCentroLayout.createSequentialGroup()
                                .addGap(5, 5, 5)
                                .addComponent(cbxFiltrar)))
                        .addGroup(pnlCentroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnlCentroLayout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addComponent(lblNombreRest, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(pnlCentroLayout.createSequentialGroup()
                                .addGap(5, 5, 5)
                                .addComponent(txtNombreRest)))
                        .addGroup(pnlCentroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnlCentroLayout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addComponent(lblCiudadRest, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(pnlCentroLayout.createSequentialGroup()
                                .addGap(2, 2, 2)
                                .addComponent(txtCiudad)))
                        .addGap(18, 18, 18)
                        .addGroup(pnlCentroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnBuscar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnSelccionar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnVerMenu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnDesceleccionar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(13, 13, 13))
                    .addComponent(lblImagenRest, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        pnlNorte.setBackground(new java.awt.Color(255, 255, 255));
        pnlNorte.setLayout(new java.awt.GridLayout(1, 0));

        lblLogo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        pnlNorte.add(lblLogo);

        pnlSur.setBackground(new java.awt.Color(255, 255, 255));
        pnlSur.setLayout(new java.awt.GridLayout(1, 0));

        tblListarRest.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nit", "Name", "Address", "Mobile", "Email", "City"
            }
        ));
        tblListarRest.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblListarRestMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tblListarRest);

        pnlSur.add(jScrollPane2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlNorte, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(pnlSur, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(pnlCentro, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(pnlNorte, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(1, 1, 1)
                .addComponent(pnlCentro, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pnlSur, javax.swing.GroupLayout.DEFAULT_SIZE, 283, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cbxFiltrarItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cbxFiltrarItemStateChanged
         habilitar();
    }//GEN-LAST:event_cbxFiltrarItemStateChanged
    public void verMenu (){
        GUIRestauranteEscogido objRestaurantEscogido  = new GUIRestauranteEscogido(restauranteSeleccionado);
        dskEscritorio.add(objRestaurantEscogido);
        try {
                objRestaurantEscogido.setMaximum(true);
            } catch (PropertyVetoException ex) {
                Logger.getLogger(GUIRestauranteEscogido.class.getName()).log(Level.SEVERE, null, ex);
            }
        try {
            this.setMaximum(false);
        } catch (PropertyVetoException ex) {
            Logger.getLogger(GUIListarRestaurantesCustomer.class.getName()).log(Level.SEVERE, null, ex);
        }
            objRestaurantEscogido.show();
    
    }
    private void btnSelccionarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSelccionarActionPerformed
        restauranteSeleccionado = restaurants.get(seleccionar);
        System.out.println("Restaurante Selecciono"+restauranteSeleccionado.getAtrNameRest());
        btnVerMenu.setEnabled(true);
        cargarLista();
        cargarDatosTabla();
    }//GEN-LAST:event_btnSelccionarActionPerformed

    private void tblListarRestMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblListarRestMouseClicked
        seleccionar = tblListarRest.rowAtPoint(evt.getPoint());
        btnVerMenu.setEnabled(false);
        System.out.println("co.unicauca.cliente.restaurantathand.presentation.GUIListarRestaurantesCustomer.tblListarRestMouseClicked()");
        System.out.println("Selecciono"+seleccionar);
    }//GEN-LAST:event_tblListarRestMouseClicked

    private void btnVerMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVerMenuActionPerformed
        verMenu();
    }//GEN-LAST:event_btnVerMenuActionPerformed


    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBuscar;
    private javax.swing.JButton btnDesceleccionar;
    private javax.swing.JButton btnSelccionar;
    private javax.swing.JButton btnVerMenu;
    private javax.swing.JComboBox<String> cbxFiltrar;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lblCiudadRest;
    private javax.swing.JLabel lblFiltrarPor;
    private javax.swing.JLabel lblImagenRest;
    private javax.swing.JLabel lblLogo;
    private javax.swing.JLabel lblNombreRest;
    private javax.swing.JPanel pnlCentro;
    private javax.swing.JPanel pnlNorte;
    private javax.swing.JPanel pnlSur;
    private javax.swing.JTable tblListarRest;
    private javax.swing.JTextField txtCiudad;
    private javax.swing.JTextField txtNombreRest;
    // End of variables declaration//GEN-END:variables
}
